# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: adsforg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dynamodb-study
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dynamodb-study

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  deploymentMethod: direct
  architecture: arm64

functions:
  hello:
    handler: src/functions/handler.handler
    events:
      - httpApi:
          path: /
          method: get
